// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306050349_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.SentimentAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AnalyzedAt");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("Confidence");

                    b.Property<string>("KeyReasons")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("KeyReasons");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Label");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ModelVersion");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("OriginalText");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("Score");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("SourceUrl");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("Symbol");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "AnalyzedAt")
                        .HasDatabaseName("IX_SentimentAnalyses_Symbol_AnalyzedAt");

                    b.ToTable("SentimentAnalyses", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
