// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Domain.Entities.SentimentAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("AnalyzedAt");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL")
                        .HasColumnName("Confidence");

                    b.Property<string>("KeyReasons")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("KeyReasons");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Label");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ModelVersion");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("OriginalText");

                    b.Property<double>("Score")
                        .HasColumnType("REAL")
                        .HasColumnName("Score");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("SourceUrl");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("Symbol");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "AnalyzedAt")
                        .HasDatabaseName("IX_SentimentAnalyses_Symbol_AnalyzedAt");

                    b.ToTable("SentimentAnalyses", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
